__author__ = 'Gayana'

SEP_PIPE='|'
SEP_COMMA=','
is_adaptive_mode = False
IS_ML_ENABLED = False
log_path="/home/ubuntu/oracle_plus.txt"
PERFORMANCE_PATH="/home/ubuntu/performace.txt"
QUORUM_MAP_PATH="/home/ubuntu/quorum_map.txt"
topk_ip="127.0.0.1"
topk_port=42000
oracle_loop_time=10
socket_receive_byte = 1000
HTTP_GET = "GET"
HTTP_PUT = "PUT"
HTTP_POST = "POST"
HTTP_DELETE = "DELETE"
HTTP_HEAD = "HEAD"
CASE_ID=<ID>
DEFAULT_READ_QUORUM = <READQ>
DEFAULT_WRITE_QUORUM = <WRITEQ>
REPLICA_COUNT=5
TOPK_ERROR_THRESHOLD_PERCENTAGE = 5
ML_IP = "127.0.0.1"
ML_PORT = 50000
PENDING_REQ_MONITOR_TIMEOUT=0.2
IS_PARALLEL_READ = True
IS_READ_PARALLEL_MAX= False
IS_CLASSIC_WRITE=True

IS_ML_TRAINING=True
