# ============================================================================
# Name        : Makefile
# Author      : sri
# Version     :
# Copyright   : 
# Description : Makefile for Hello World in Fortran
# ============================================================================



samplemake: src/sample.c
	gcc  -g -o sample src/sample.c -lm