__author__ = 'Gayana'

SEP_PIPE='|'
SEP_COMMA=','
is_adaptive_mode = <is_adaptive_mode>
IS_ML_ENABLED = <IS_ML_ENABLED>
IS_STATIC_POLICY_ENABLED=<IS_STATIC_POLICY_ENABLED>
log_path="/home/ubuntu/oracle_plus.txt"
PERFORMANCE_PATH="/home/ubuntu/performace.txt"
QUORUM_MAP_PATH="/home/ubuntu/quorum_map.txt"
topk_ip="<topk_ip>"
topk_port=<topk_port>
oracle_loop_time=<oracle_loop_time>
socket_receive_byte = <socket_receive_byte>
HTTP_GET = "GET"
HTTP_PUT = "PUT"
HTTP_POST = "POST"
HTTP_DELETE = "DELETE"
HTTP_HEAD = "HEAD"
DEFAULT_READ_QUORUM = <DEFAULT_READ_QUORUM>
DEFAULT_WRITE_QUORUM = <DEFAULT_WRITE_QUORUM>
REPLICA_COUNT=<REPLICA_COUNT>
TOPK_ERROR_THRESHOLD_PERCENTAGE = <TOPK_ERROR_THRESHOLD_PERCENTAGE>
ML_IP = "<ML_IP>"
ML_PORT = <ML_PORT>
PENDING_REQ_MONITOR_TIMEOUT=<PENDING_REQ_MONITOR_TIMEOUT>
IS_PARALLEL_READ = <IS_PARALLEL_READ>
IS_READ_PARALLEL_MAX= <IS_READ_PARALLEL_MAX>
IS_CLASSIC_WRITE=<IS_CLASSIC_WRITE>

IS_ML_TRAINING=<IS_ML_TRAINING>
CASE_ID=<CASE_ID>

PROCESSED_LOG_PATH="/home/ubuntu/processed.txt"
SENT_LOG_PATH="/home/ubuntu/sent.txt"
IS_TEST_COMMUNICATION=<IS_TEST_COMMUNICATION>
IS_MASTER = <IS_MASTER>
CURRENT_IP = "<CURRENT_IP>"
MASTER_IP = "<MASTER_IP>"
SLAVE_IPS=<SLAVE_IPS>
LISTENING_PORT=<LISTENING_PORT>

SIZE=<SIZE>
COLLECT_BEST=<COLLECT_BEST>
All_BEST=<All_BEST>

ENABLE_LOGS=<ENABLE_LOGS>
